version: '3.3'

services:
  houseTagir:
    build: ./
    command: ./houseTagir
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "houseTagir"
      POSTGRES_PASSWORD: 123
    ports:
      - "5436:5432"